# This is a basic workflow to help you get started with Actions

name: Homebrew Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install jq
      - name: Install jq
        shell: bash
        run: |
          sudo apt-get install -y 

      # validate json
      - name: Validate json
        shell: bash
        run: |
          VALIDATE_COMMAND="jq type test.json"
          VALIDATE_RESULT=$(eval "$VALIDATE_COMMAND")

          if VALIDATE_RESULT=='"object"'; then
            echo "{JSON_IS_VALID}={true}" >> $GITHUB_ENV
          else
            echo "{JSON_IS_VALID}={false}" >> $GITHUB_ENV
          fi

      # warning
      - name: Warning json
        if: ${{ env.JSON_IS_VALID == 'false' }}
        shell: bash
        run: |
          echo "コラッ"
          
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
